### ISSUE TITLE
Is there any documentation on how to get started using this library?

### ISSUE THREAD

**Issue by ppazos** [cucumber/cucumber-jvm-groovy#10]
I'm need to check what this library offers vs. using cucumber-jvm directly. Thanks.

**Comment by glib-briia** [comment]
Hi @ppazos ,

I'm working on creating some. Wont me much different to how cucumber-jwm is used. 
You can take a look at [example project](https://github.com/cucumber/cucumber-jvm-groovy/tree/master/examples) before I get documentation ready.

**Comment by ppazos** [comment]
Thanks @glib-briia did you check the old cucumber-groovy project?

**Comment by ppazos** [comment]
@glib-briia tested the project, mvn test throws

[```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:52 min
[INFO] Finished at: 2018-12-29T00:30:10-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project groovy-examples: Could not resolve dependencies for project io.cucumber:groovy-examples:jar:4.2.1-SNAPSHOT: Could not find artifact io.cucumber:cucumber-groovy:jar:4.2.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by mlvandijk** [comment]
You could check the [docs](https://docs.cucumber.io/) if the setup would be similar to Java.

**Comment by ppazos** [comment]
@mlvandijk did you tried it? I already read the docs. This is as far as I could get. Maybe you have better luck and can give more specific feedback.

**Comment by mlvandijk** [comment]
@ppazos Sorry, I don't use Groovy (only Java and Kotlin).
I can build this project locally though (current master), using `mvn clean install`.
Since your error message is saying it cannot find the SNAPSHOT; did you check you have the snapshot built locally?

**Comment by glib-briia** [comment]
Hi @ppazos ,

That's right, example project is child of cucumber-jvm-groovy, so you'll need to run `mvn install` in the root of the repository (e.g. `cd cucumber-jvm-groovy & mvn install`).

**Comment by glib-briia** [comment]
Documentation added to README.md
