### ISSUE TITLE
Parametrized types as step parameters wont work

### ISSUE THREAD

**Issue by gabrielps** [cucumber/cucumber-jvm-groovy#14]
I tried to build a TableRowTransformer and could not make it work.
`DataTableTypeRegistryTableConverter.convert()` will `DataTableTypeRegistryTableConverter.lookupTableTypeByType()` but won't resolve the bindings as it will `TypeFactory.constructType()` and `jackson.TypeFactory.constructType()` will `return _fromAny(null, type, EMPTY_BINDINGS);`

**Comment by gabrielps** [comment]
Damn it. I got the answer. 
After registering a TableRowTransformer you have to make `dataTable.asList(Type)`.
Thanks anyways :)

**Comment by glib-briia** [comment]
Glad it's sorted:) any further questions let me know
