### ISSUE TITLE
Issue with compiled groovy step definitions

### ISSUE THREAD

**Issue by SMUnlimited** [cucumber/cucumber-jvm-groovy#17]
Groovy 2.4.17
Cucumber-groovy 4.2.0

Code for loading compiled groovy step definitions does the below step:

https://github.com/cucumber/cucumber-jvm-groovy/blob/bebcc84db62b83adf463f810c9cb221e20212251/groovy/src/main/java/cucumber/runtime/groovy/GroovyBackend.java#L92

Unfortunately the default behaviour for non-class compiled groovy is to add a "NoArg" constructor. There is no constructor that takes a binding object argument unless you manually make your step definition a class with this constructor defined beforehand. Otherwise the below error occurs when loading step defs

```
Caused by: java.lang.NoSuchMethodException: org.MyStepDefs.<init>(groovy.lang.Binding)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at cucumber.runtime.groovy.GroovyBackend.loadGlue(GroovyBackend.java:89)
```

In theory just needs to be changed to newInstance() and will solve the issue.

**Comment by glib-briia** [comment]
Hi @SMUnlimited , Could you please provide us with example of your stepdefs file (obfuscate if any sensitive data)?

**Comment by SMUnlimited** [comment]
Actually after getting the code i wonder if its something to do with setting a scriptBase in groovy compiler configuration "setScriptBaseClass". 

Source
{code}
package mypackage

import io.cucumber.datatable.DataTable

this.metaClass.mixin(cucumber.api.groovy.Hooks)
this.metaClass.mixin(cucumber.api.groovy.EN)

import static cucumber.api.groovy.EN.*

Before('@config') { feature ->

}

After('@deletedconfigs') { feature ->
  // to delete
}

When(~/^I navigate to the Page$/) { ->
    assert true
}

Then(~/^sorted alphabetically$/) { ->
    assert false
}
{code}

Compiled (Decompiled by Intellij)
{code}

package mypackage;

import mypackage.ScriptBase;
import cucumber.api.groovy.EN;
import cucumber.api.groovy.Hooks;
import groovy.lang.Closure;
import org.codehaus.groovy.runtime.GeneratedClosure;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;
import org.codehaus.groovy.runtime.powerassert.AssertionRenderer;
import org.codehaus.groovy.runtime.powerassert.ValueRecorder;

public class MyStepDefs extends ScriptBase {
    public MyStepDefs() {
        CallSite[] var1 = $getCallSiteArray();
        super();
    }

    public static void main(String... args) {
        CallSite[] var1 = $getCallSiteArray();
        var1[0].call(InvokerHelper.class, MyStepDefs.class, args);
    }

    public Object internalRun() {
        CallSite[] var1 = $getCallSiteArray();
        var1[1].call(var1[2].callGroovyObjectGetProperty(this), Hooks.class);
        var1[3].call(var1[4].callGroovyObjectGetProperty(this), EN.class);

        class _internalRun_closure1 extends Closure implements GeneratedClosure {
            public _internalRun_closure1(Object _outerInstance, Object _thisObject) {
                CallSite[] var3 = $getCallSiteArray();
                super(_outerInstance, _thisObject);
            }

            public Object doCall(Object feature) {
                CallSite[] var2 = $getCallSiteArray();
                return null;
            }
        }

        var1[5].callCurrent(this, "@config", new _internalRun_closure1(this, this));

        class _internalRun_closure2 extends Closure implements GeneratedClosure {
            public _internalRun_closure2(Object _outerInstance, Object _thisObject) {
                CallSite[] var3 = $getCallSiteArray();
                super(_outerInstance, _thisObject);
            }

            public Object doCall(Object feature) {
                CallSite[] var2 = $getCallSiteArray();
                return null;
            }
        }

        var1[6].callCurrent(this, "@deletedconfigs", new _internalRun_closure2(this, this));

        class _internalRun_closure3 extends Closure implements GeneratedClosure {
            public _internalRun_closure3(Object _outerInstance, Object _thisObject) {
                CallSite[] var3 = $getCallSiteArray();
                super(_outerInstance, _thisObject);
            }

            public Object doCall() {
                CallSite[] var1 = $getCallSiteArray();
                ValueRecorder var2 = new ValueRecorder();

                try {
                    if (true) {
                        var2.clear();
                    } else {
                        ScriptBytecodeAdapter.assertFailed(AssertionRenderer.render("assert true", var2), (Object)null);
                    }

                    return null;
                } catch (Throwable var4) {
                    var2.clear();
                    throw var4;
                }
            }
        }

        var1[7].callStatic(EN.class, ScriptBytecodeAdapter.bitwiseNegate("^I navigate to the Page$"), new _internalRun_closure3(this, this));

        class _internalRun_closure4 extends Closure implements GeneratedClosure {
            public _internalRun_closure4(Object _outerInstance, Object _thisObject) {
                CallSite[] var3 = $getCallSiteArray();
                super(_outerInstance, _thisObject);
            }

            public Object doCall() {
                CallSite[] var1 = $getCallSiteArray();
                ValueRecorder var2 = new ValueRecorder();

                try {
                    if (false) {
                        var2.clear();
                    } else {
                        ScriptBytecodeAdapter.assertFailed(AssertionRenderer.render("assert false", var2), (Object)null);
                    }

                    return null;
                } catch (Throwable var4) {
                    var2.clear();
                    throw var4;
                }
            }
        }

        return var1[8].callStatic(EN.class, ScriptBytecodeAdapter.bitwiseNegate("^sorted alphabetically$"), new _internalRun_closure4(this, this));
    }
}
{code}

**Comment by SMUnlimited** [comment]
The groovy scriptbase script we use looks like:

``
package mypackage

abstract class ScriptBase extends Script {
	/**
	 * Script entry point.
	 */
	def run() {
		preRun()
		internalRun()
	}

	def preRun() {
		println("prerun")
	}

	/**
	 * Script code automatically overrides this method.
	 */
	abstract def internalRun()
}
```

**Comment by glib-briia** [comment]
thank you for detailed info .Could you please share where exactly are you setting setScriptBaseClass?

**Comment by glib-briia** [comment]
Could you try adding a constructor to your custom script base as per below:
```
package mypackage
abstract class ScriptBase extends Script {
    /**
     * Script entry point.
     */
    ScriptBase(Binding binding) {
        super(binding)
    }

    def run() {
        preRun()
        internalRun()
    }

    def preRun() {
        println("prerun")
    }

    /**
     * Script code automatically overrides this method.
     */
    abstract def internalRun()
}
```

**Comment by SMUnlimited** [comment]
> Could you try adding a constructor to your custom script base as per below:

That seems to work

**Comment by glib-briia** [comment]
Glad its resolved now. Closing.
