### ISSUE TITLE
Upgrade plans for cucumber-jvm 5.x.x

### ISSUE THREAD

**Issue by ice1080** [cucumber/cucumber-jvm-groovy#19]
I was wondering if there are any plans to upgrade this to work with cucumber-jvm 5.x.x (or any documentation on how to use them together if it already works). We absolutely love cucumber-groovy and have near 6000 selenium scenarios running in a kubernetes cluster. Would love to see this project continue getting updated!

**Comment by glib-briia** [comment]
Hi ice1080,

Great to here that it's being used! 
I've almost finished the migration. There is one issue left with inferred parameters. I think there will be beta available in next couple weeks.

**Comment by ice1080** [comment]
Great to hear! If there is anything you are wanting someone else to work on, I may be able to assist a bit if you want to create issues or something to track them.

**Comment by glib-briia** [comment]
Cucumber-groovy is now updated to v5.1.3 and waiting to be released.

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-jvm-groovy/commit/ad3c7600b43cc08af155ac21003fd122e7f27c0b was released. Should be available from central in a hour so.
