### ISSUE TITLE
Publish 6.1.1-SNAPSHOT to maven

### ISSUE THREAD

**Issue by Niimaat** [cucumber/cucumber-jvm-groovy#21]
Hi,

I just noticed that there are some changes that are yet to be published to maven. Specifically changes in this commit: https://github.com/cucumber/cucumber-jvm-groovy/commit/f6de85a29929923410fd7a69ea1f87d174a522fe. Can anyone assist in publishing this to maven.

Thanks in advance.

**Comment by glib-briia** [comment]
Hi @mpkorstanje ,

Could you please release v 6.1.1 when you got a minute.

**Comment by glib-briia** [comment]
Version 6.1.1 is now released. Will be available in maven shortly.
