### ISSUE TITLE
Command line in Readme.md should work

### ISSUE THREAD

**Issue by dbenjamingrs** [cucumber/cucumber-jvm-groovy#3]
For me, the command near the top of Readme.md needed modification before it worked.

On Mac OS X after cloning `cucumber-jvm-groovy`, the following command sequence worked for me

`$ brew install groovy`
`$ export GROOVY_HOME=/usr/local/opt/groovy/libexec`
`$ mvn install`
`$ cd groovy`
`$ groovy -cp target/test-classes ./bin/cucumber-jvm.groovy --glue src/test/resources --glue src/test/groovy src/test/resources/cucumber/runtime/groovy/a_feature.feature`

where the second `--glue` parameter, `--glue src/test/groovy`,  is modified from what is in Readme.md, `--glue cucumber/runtime/groovy`

**Comment by mpkorstanje** [comment]
Hey thanks for reporting this!

Could you provide this as PR? You can quickly create one online by opening [README.md](https://github.com/cucumber/cucumber-jvm-groovy/blob/master/README.md) and hitting the edit button.

This makes fixing things easier, and creates attribution.
