### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by asiekierka** [cucumber/cucumber-jvm-groovy#4]
What is the license of this package? Does not seem to be immediately clear, unlike Cucumber itself which seems to be licensed [under the MIT/X11 license](https://github.com/cucumber/cucumber-jvm/blob/master/LICENCE).

**Comment by mpkorstanje** [comment]
It is licensed under the same license as cucumber-jvm. Groovy was recently split off. 

Due to low usage numbers the core team decided to drop support for groovy. As such this project is looking for maintainers.
